# Stateless application
common:
  annotations: ~
  labels: ~
  env: ~
  secret: ~ # secret is a env but private
  image:
    registry: registry-1.docker.io
    repository: ~
    tag: ~
    pullSecrets: ~
app:
  enabled: true
  name: ~ # required
  image:
    registry: ~
    repository: ~
    tag: ~
    pullSecrets: ~
  commands: ~
  args: ~
  port: 80
  annotations: ~
  labels: ~
  ingress:
    enabled: true
    annotations: ~
    labels: ~
    className: ~
    host: ~
    path: /
    pathType: ~
    tls: ~
  replicas:
    autoScalingEnabled: true
    replicaCount: 1
    minReplicas: 0
    maxReplicas: 3
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env: ~
  secret: ~
  # affinity:
  # placement: {}
  jobs:
    - enabled: true
      name: ~ # required
      image:
        registry: ~
        repository: ~
        tag: ~
        pullSecrets: ~
      commands: ~
      args: ~
      events: ~
      env: ~
      secret: ~
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
  extras:
    # -
workers:
  - enabled: true
    name: "" # required
    labels: ~
    annotations: ~
    image:
      registry: ~
      repository: ~
      tag: ~
      pullSecrets: ~
    commands: ~
    args: ~
    replicas:
      autoScalingEnabled: true
      replicaCount: 1
      minReplicas: 0
      maxReplicas: 3
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    env: ~
    secret: ~ # secret is a env but private
    affinity: ~
    placement: ~
    extras: ~

extras:
  ~
  #- k8s defination
