# Stateless application
common:
  annotations: ~
  labels: ~
  env: ~
  secret: ~ # secret is a env but private
  image:
    registry: registry-1.docker.io
    repository: traefik/whoami
    tag: latest
    # pullSecrets:
    #   - name: "__string__"
app:
  enabled: true
  name: rails
  image:
    registry: ~
    repository: ~
    tag: ~
    pullSecrets: ~
  commands: ~
  args: ~
  port: 80
  annotations: ~
  labels: ~
  ingress:
    enabled: true
    annotations: ~
    labels: ~
    className: ~
    host: ~
    path: /
    pathType: ~
    tls: ~
  replicas:
    autoScalingEnabled: true
    replicaCount: 1
    minReplicas: 0
    maxReplicas: 10
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env: ~
  secret: ~
  # affinity:
  # placement: {}
  jobs:
    - enabled: true
      name: database-migration
      image:
        registry: ~
        repository: ~
        tag: ~
        pullSecrets: ~
      commands:
        - sleep
        - "1"
      events: # helm event
        - pre-install
      env: ~
      secret: ~
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
  extras:
    # -
workers:
  # - enabled: true
  #   name: ~
  #   labels: ~
  #   annotations: ~
  #   image:
  #     registry: ~
  #     repository: ~
  #     tag: ~
  #     pullSecrets: ~
  #   commands:
  #     - /bin/top
  #   args: ~
  #   replicas:
  #     autoScalingEnabled: true
  #     replicaCount: 1
  #     minReplicas: 0
  #     maxReplicas: 10
  #   resources:
  #     limits:
  #       cpu: 100m
  #       memory: 128Mi
  #     requests:
  #       cpu: 100m
  #       memory: 128Mi
  #   env: ~
  #   secret: ~ # secret is a env but private
  #   affinity: ~
  #   placement: ~
  #   extras: ~

extras: ~
