# Stateless application
common:
  image:
    registry: registry-1.docker.io
app:
  enabled: true
  name: whoami
  image:
    repository: traefik/whoami #
    tag: latest
  port: 80
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/service.nativelb: "true"
    className: traefik
    path: /
    pathType: "Prefix"
  jobs:
    - enabled: true
      name: database-migration
      image:
        repository: library/busybox #
        tag: latest
      commands:
        - sleep
        - "1"
      events: # helm event
        - pre-install
workers:
  - enabled: true
    name: "top"
    image:
      repository: library/busybox #
      tag: "latest"
    commands:
      - /bin/top
