---
# Source: web-application/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: abc
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release-name: abc
    app.kubernetes.io/chart: web-application-0.1.0     
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: abc
---
# Source: web-application/templates/deployment.yaml
# App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release-name: abc
    app.kubernetes.io/chart: web-application-0.1.0 
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: abc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: abc
    spec:
      containers: 
      - name:  app-whoami
        image: registry-1.docker.io/traefik/whoami:latest
        ports:
          - containerPort: 80
            protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
 # Worker
---
# Source: web-application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-worker-top
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release-name: abc
    app.kubernetes.io/chart: web-application-0.1.0 
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: abc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: abc
    spec:
      containers: 
        - name: worker-top
          image: registry-1.docker.io/library/busybox:latest
          command: ["/bin/top"]
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
# Source: web-application/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abc
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release-name: abc
    app.kubernetes.io/chart: web-application-0.1.0
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: let-encrypt
    traefik.ingress.kubernetes.io/service.nativelb: "true" 
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix 
            backend:
              service:
                name: abc
                port:
                  number: 80
      host: "whoami.3.1.243.29.traefik.me"
---
# Source: web-application/templates/jobs.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: abc-job-database-migration
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release-name: abc
    app.kubernetes.io/chart: web-application-0.1.0
  annotations:
    helm.sh/hook: pre-install
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: abc 
    spec:
      backoffLimit: 1
      restartPolicy: Never
      containers:
        - name: job-database-migration
          image: registry-1.docker.io/library/busybox:latest
          imagePullPolicy: Always
          command:
            - sleep
            - "1"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
