# Stateless application
common:
  image:
    registry: registry-1.docker.io
app:
  enabled: true
  name: whoami
  image:
    repository: traefik/whoami #
    tag: latest
  port: 80
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls.certresolver: let-encrypt
      traefik.ingress.kubernetes.io/service.nativelb: "true"
    className: traefik
    host: whoami.3.1.243.29.traefik.me
    path: /
    pathType: "Prefix"
  replicas:
    autoScalingEnabled: true
    replicaCount: 1
    minReplicas: 0
    maxReplicas: 10
  jobs:
    - enabled: true
      name: database-migration
      image:
        repository: library/busybox #
        tag: latest
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      replicas:
        autoScalingEnabled: true
        replicaCount: 1
        minReplicas: 0
        maxReplicas: 10
      commands:
        - sleep
        - "1"
      events: # helm event
        - pre-install
workers:
  - enabled: true
    name: "top"
    image:
      repository: library/busybox #
      tag: "latest"
    commands:
      - /bin/top
    replicas:
      autoScalingEnabled: true
      replicaCount: 1
      minReplicas: 0
      maxReplicas: 10
