common:
  annotations: {}
  labels: {}
  env: {}
  secret: {}
  image:
    registry: "registry-1.docker.io"
    repository: "traefik/whoami"
    tag: "latest"

app:
  enabled: true
  name: "my-app"
  image:
    registry: ~
    repository: ~
    tag: ~
    pullSecrets: []
  commands: []
  args: []
  port: 80
  annotations: {}
  labels: {}
  ingress:
    enabled: false
    annotations: {}
    labels: {}
    className: "nginx"
    host: "my-app.example.com"
    path: "/app"
    pathType: "Prefix"
    tls: ""
  replicas:
    autoScalingEnabled: false
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 75
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  env:
    APP_ENV_VAR: "value"
  secret: {}
  jobs:
    - enabled: false
      name: "job#1"
      image:
        registry: ~
        repository: ~
        tag: ~
        pullSecrets: []
      commands: ~
      args: []
      events: []
      env: {}
      secret: {}
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
  extras: ~

workers:
  - enabled: false
    name: "worker#1"
    labels: {}
    annotations: {}
    image:
      registry: ~
      repository: ~
      tag: ~
      pullSecrets: []
    commands: []
    args: []
    replicas:
      autoScalingEnabled: false
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 4
      targetCPUUtilizationPercentage: 75
      targetMemoryUtilizationPercentage: 75
    resources:
      limits:
        cpu: "150m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    env: {}
    secret: {}
    affinity: ~
    placement: ~
    extras: ~

extras: ~
