# Stateless application
common:
  image:
    registry: registry-1.docker.io
apps:
  - enabled: true
    name: whoami
    image:
      repository: traefik/whoami #
      tag: latest
    port: 80
    replicas:  
      autoScalingEnabled: true
      maxReplicas: 3
      minReplicas: 1
    jobs:
      - enabled: true
        name: database-migration
        image:
          repository: library/busybox #
          tag: latest
        commands:
          - sleep
          - "1"
        events: # helm event
          - pre-install
workers:
  - enabled: true
    name: "top"
    image:
      repository: library/busybox #
      tag: "latest"
    commands:
      - /bin/top
