---
# Source: universal-web-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release-name: abc
    app.kubernetes.io/chart: universal-web-app-0.1.8 
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: abc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: abc
    spec:
      containers: 
      - name:  app-%!s(<nil>)
        image: registry-1.docker.io/traefik/whoami:latest
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
 # Worker
---
# Source: universal-web-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-worker-top
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release-name: abc
    app.kubernetes.io/chart: universal-web-app-0.1.8 
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: abc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: abc
    spec:
      containers: 
        - name: worker-top
          image: registry-1.docker.io/library/busybox:latest
          command: ["/bin/top"]
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
# Source: universal-web-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abc
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release-name: abc
    app.kubernetes.io/chart: universal-web-app-0.1.8 
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /app
            pathType: Prefix 
            backend:
              service:
                name: abc
                port:
                  number: 80
      host: "my-app.example.com"
---
# Source: universal-web-app/templates/deployment.yaml
# App
