---
# Source: universal-web-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels: 
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release-name: abc
    app.kubernetes.io/chart: universal-web-app-0.1.8
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: abc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: abc
    spec:
      containers: 
      - name:  app-whoami
        image: registry-1.docker.io/traefik/whoami:latest
        command:
          
        args:
          
        ports:
          - containerPort: 
            protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi

## Worker
---
# Source: universal-web-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-worker-top
  labels: 
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release-name: abc
    app.kubernetes.io/chart: universal-web-app-0.1.8
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: abc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: abc
    spec:
      containers: 
        - name: worker-top
          image: registry-1.docker.io/library/busybox:latest
          command:
            - /bin/top
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
# Source: universal-web-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abc
  labels: 
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release-name: abc
    app.kubernetes.io/chart: universal-web-app-0.1.8
spec:
  ingressClassName: traefik
  tls:
  - hosts: 
    - 
    secretName:  
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix 
            backend:
              service:
                name: abc
                port:
                  number: 80
      host: ""
---
# Source: universal-web-app/templates/deployment.yaml
# Deployment
## App
---
# Source: universal-web-app/templates/extras.yaml
# Extra
---
# Source: universal-web-app/templates/hpa.yaml
# HPA
## App

## Worker
---
# Source: universal-web-app/templates/ingress.yaml
# Ingress
---
# Source: universal-web-app/templates/jobs.yaml
# Jobs
---
# Source: universal-web-app/templates/secret.yaml
# Secret
---
# Source: universal-web-app/templates/jobs.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: abc-job-database-migration
  labels: 
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release-name: abc
    app.kubernetes.io/chart: universal-web-app-0.1.8
  annotations:
    helm.sh/hook: pre-install
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: abc 
    spec:
      restartPolicy: Never
      containers:
        - name: job-database-migration
          image: registry-1.docker.io/library/busybox:latest
          imagePullPolicy: Always
          command:
            - sleep
            - "1"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
