# App
{{- with .Values.app }}
{{- if (.enabled | default true) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  {{- with include "get.labels.full" (list $ .labels) }}
  labels:
    {{- . | nindent 4 }}
  {{- end}}
  {{- with include "get.annotations" (list $ .annotations) }}
  annotations: 
    {{- . | nindent 4 }}
  {{- end}} 
spec:
  {{- with (include "template.replicas" (.replicas | default dict)| fromYaml )}}
  {{- if not .autoScalingEnabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- (include "get.labels.selector" (list $ .labels) )| nindent 6 }}
  template:
    metadata:
      labels: 
        {{- (include "get.labels.selector" (list $ .labels)) | nindent 8 }}
    spec:
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "get.image_pull_secrets" (list $ .pullSecrets) )}}
      imagePullSecrets: 
        {{- . | nindent 8}}
      {{- end }}
      containers: 
      - name:  {{printf "app-%s" .name}}
        image: {{ include "get.image_url" (list $ .image) }}
        {{- with .commands }}
        command: {{ toJson . }}
        {{- end }}
        {{- with .args }}
        args: {{ toJson . }}
        {{- end }}
        {{- with .port}}
        ports:
          - containerPort: {{ . }}
            protocol: TCP
        {{- end }}
        resources:
          {{- include "template.resources" (.resources | default dict ) | nindent 10}}
        {{- if or $.Values.common.env .env }}
        env:
          {{- with $.Values.common.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if or .secret $.Values.common.secret }}
        envFrom:
          {{- with .secret}}
          - secretRef:
              name: {{ include "application.fullname" $ }}-app
          {{- end }}
          {{- with $.Values.common.secret}}
          - secretRef:
              name: {{ include "application.fullname" $ }}-common
          {{- end }}
        {{- end }}
{{- end }}
{{- end }}
 # Worker
{{- range .Values.workers }}
---
{{- if (.enabled | default true) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{printf "%s-worker-%s" (include "application.fullname" $) (.name)}}
  {{- with include "get.labels.full" (list $ .labels) }}
  labels:
    {{- . | nindent 4 }}
  {{- end}}
  {{- with include "get.annotations" (list $ .annotations) }}
  annotations: 
    {{- . | nindent 4 }}
  {{- end}} 
spec:
  {{- with (include "template.replicas" (.replicas | default dict)| fromYaml )}}
  {{- if not .autoScalingEnabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- (include "get.labels.selector" (list $ .labels) )| nindent 6 }}
  template:
    metadata:
      labels: 
        {{- (include "get.labels.selector" (list $ .labels)) | nindent 8 }}
    spec:
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "get.image_pull_secrets" (list $ .pullSecrets) )}}
      imagePullSecrets: 
        {{- . | nindent 8}}
      {{- end }}
      containers: 
        - name: {{printf "worker-%s" .name}}
          image: {{ include "get.image_url" (list $ .image) }}
          {{- with .commands }}
          command: {{ toJson . }}
          {{- end }}
          {{- with .args }}
          args: {{ toJson . }}
          {{- end }}
          {{- if or $.Values.common.env .env }}
          env:
            {{- with $.Values.common.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if or .secret $.Values.common.secret }}
          envFrom:
            {{- with $.Values.common.secret}}
            - secretRef:
                name: {{ include "application.fullname" $ }}-common
            {{- end }}
            {{- with .secret}}
            - secretRef:
                name: {{ printf "%s-job-%s" (include "application.fullname" $) (.name)}}
            {{- end }}
          {{- end }}
          resources:
            {{- include "template.resources" (.resources | default dict ) | nindent 12}}
{{- end }}    
{{- end }} 