  
{{- with .Values.common.secret }}
{{- if . }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "application.fullname" $ }}-common
  labels:
    {{- include "application.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-9999"
    "helm.sh/hook": "pre-install"

data:
  {{- range $k, $v := . }}
  {{ $k }}: {{ $v | default "" | b64enc }}
  {{- end }}
{{- end }}
{{- end }}

{{- with .Values.app.secret }}
{{- if . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "application.fullname" $ }}-app
  labels:
    {{- include "application.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-9999"
    "helm.sh/hook": "pre-install"
data:
  {{- range $k, $v := . }}
  {{ $k }}: {{ $v | default "" | b64enc }}
  {{- end }}
{{- end }}
{{- end }}

{{- range .Values.app.jobs }}
{{- if .secret }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-job-%s" (include "application.fullname" $) (.name)}}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-9999"
    "helm.sh/hook": "pre-install"
data:
  {{- range $k, $v := .secret }}
  {{ $k }}: {{ $v | default "" | b64enc }}
  {{- end }}
{{- end }}
{{- end }}

{{- range .Values.workers }}
{{- if .secret }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-job-%s" (include "application.fullname" $) (.name)}}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-9999"
    "helm.sh/hook": "pre-install"
data:
  {{- range $k, $v := .secret }}
  {{ $k }}: {{ $v | default "" | b64enc }}
  {{- end }}
{{- end }} 
{{- end }} 
