{{- range .Values.apps }}
{{- with (include "template.app" (. | default dict)| fromYaml )}}
{{- if (.enabled | default true) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  {{- with include "get.labels.full" (list $ .labels) }}
  {{- . | nindent 2 }}
  {{- end}}
  {{- with include "get.annotations" (list $ .annotations) }}
  {{- . | nindent 2 }}
  {{- end}}
spec:
  {{- with (include "template.replicas" (.replicas | default dict)| fromYaml )}}
  {{- if not .autoScalingEnabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- (include "get.labels.selector" (list $ .labels) )| nindent 6 }}
  template:
    metadata:
      labels: 
        {{- (include "get.labels.selector" (list $ .labels)) | nindent 8 }}
    spec:
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "get.image_pull_secrets" (list $ .image) )}}
      imagePullSecrets: 
        {{- . | nindent 8}}
      {{- end }}
      containers: 
      - name:  {{printf "app-%s" .name}}
        image: {{ include "get.image_url" (list $ .image) }}
        {{- with .commands }}
        {{- if . }}
        command:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- with .args }}
        {{- if . }}
        args:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- with .port}}
        ports:
          - containerPort: {{ . }}
            protocol: TCP
        {{- end }}
        resources:
          {{- include "template.resources" (.resources | default dict ) | nindent 10}}
        {{- if or $.Values.common.env .env }}
        env:
          {{- range $k,$v := $.Values.common.env}}
          - name: {{$k}}
            value: {{$v}}
          {{- end }}
          {{- range $k,$v := .env}}
          - name: {{$k}}
            value: {{$v}}
          {{- end }}
        {{- end }}
        {{- if or .secret $.Values.common.secret }}
        envFrom:
          {{- with .secret}}
          - secretRef:
              name: {{ include "application.fullname" $ }}-app
          {{- end }}
          {{- with $.Values.common.secret}}
          - secretRef:
              name: {{ include "application.fullname" $ }}-common
          {{- end }}
        {{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- range .Values.workers }}
{{- with (include "template.worker" (. | default dict)| fromYaml )}}
---
{{- if (.enabled | default true) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{printf "%s-worker-%s" (include "application.fullname" $) (.name)}}
  {{- with include "get.labels.full" (list $ .labels) }}
  {{- . | nindent 2 }}
  {{- end}}
  {{- with include "get.annotations" (list $ .annotations) }}
  {{ . | nindent 2 }}
  {{- end}}
spec:
  {{- with (include "template.replicas" (.replicas | default dict)| fromYaml )}}
  {{- if not .autoScalingEnabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- (include "get.labels.selector" (list $ .labels) )| nindent 6 }}
  template:
    metadata:
      labels: 
        {{- (include "get.labels.selector" (list $ .labels)) | nindent 8 }}
    spec:
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "get.image_pull_secrets" (list $ .image) )}}
      imagePullSecrets: 
        {{- . | nindent 8}}
      {{- end }}
      containers: 
        - name: {{printf "worker-%s" .name}}
          image: {{ include "get.image_url" (list $ .image) }}
          {{- with .commands }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or $.Values.common.env .env }}
          env:
            {{- range $k,$v := $.Values.common.env}}
            - name: {{$k}}
              value: {{$v}}
            {{- end }}
            {{- range $k,$v := .env}}
            - name: {{$k}}
              value: {{$v}}
            {{- end }}
          {{- end }}
          {{- if or .secret $.Values.common.secret }}
          envFrom:
            {{- with $.Values.common.secret}}
            - secretRef:
                name: {{ include "application.fullname" $ }}-common
            {{- end }}
            {{- with .secret}}
            - secretRef:
                name: {{ printf "%s-job-%s" (include "application.fullname" $) (.name)}}
            {{- end }}
          {{- end }}
          resources:
            {{- include "template.resources" (.resources | default dict ) | nindent 12}}
{{- end }}    
{{- end }} 
{{- end }} 