{{range .Values.extras}}
---
{{- toYaml .}}
{{- end }}

{{range .Values.apps}}
{{range .extras}}
---
{{- toYaml .}}
{{- end }}

{{range .Values.workers}}
{{range .extras}}
---
{{- toYaml .}}
{{- end }}
{{- end }}