{{- range $index, $app := .Values.apps }}
{{- with (include "template.ingress" ($app.ingress | default dict) | fromYaml )}}
{{- if and .enabled $app.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application.fullname" $ }}
  {{- with include "get.labels.full" (list $ .labels) }}
  {{- . | nindent 2 }}
  {{- end}}
  {{- with include "get.annotations" (list $ .annotations) }}
  {{- . | nindent 2 }}
  {{- end}}
spec:
  {{- with .className  }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if and .tls .host  }}
  tls:
  - hosts: 
    - {{ .host }}
    secretName:  {{ .tls }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: {{ .path }}
            pathType: {{ .pathType | default "ImplementationSpecific" }} 
            backend:
              service:
                name: {{ include "application.fullname" $ }}
                port:
                  number: {{ $app.port }}
      {{- with .host }}
      host: {{ . | quote }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}