{{ range .Values.apps }}
{{- with (include "template.app" (. | default dict)| fromYaml )}}
{{ range .jobs }}
{{- with (include "template.job" (. | default dict)| fromYaml )}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{printf "%s-job-%s" (include "application.fullname" $) .name}}
  {{- with include "get.labels.full" (list $ .labels) }}
  {{- . | nindent 2 }}
  {{- end}}
  {{- if or (include "get.annotations" (list $ .annotations)) .events }}
  annotations: 
    {{- with include "get.annotations" (list $ .annotations) }}
    {{- . | nindent 4 }}
    {{- end}}
    {{- if .events}}
    helm.sh/hook: {{ join "," .events }}
    {{- end }}
  {{- end }}
spec:
  {{- with .backoffLimit | default 1}}
  backoffLimit: {{ . }}
  {{- end }}
  template:
    metadata:
      {{- with include "get.labels.selector" (list $ .labels) }}
      labels:
        {{- . | nindent 8 }}
      {{- end}}
      {{- with include "get.annotations" (list $ .annotations) }}
      annotations: 
        {{- . | nindent 8 }}
      {{- end}} 
    spec:
      restartPolicy: Never
      {{- with (include "get.image_pull_secrets" (list $ .image) )}}
      imagePullSecrets: 
        {{- . | nindent 8}}
      {{- end }}
      containers:
        - name: {{printf "job-%s" .name}}
          image: {{ include "get.image_url" (list $ .image) }}
          imagePullPolicy: Always
          {{- if or $.Values.common.env .env }}
          env:
            {{- range $k,$v := $.Values.common.env}}
            - name: {{$k}}
              value: {{$v}}
            {{- end }}
            {{- range $k,$v := .env}}
            - name: {{$k}}
              value: {{$v}}
            {{- end }}
          {{- end }}
          {{- if or .secret $.Values.common.secret }}
          envFrom:
            {{- with .secret}}
            - secretRef:
                name: {{ printf "%s-job-%s" (include "application.fullname" $) (.name)}}
            {{- end }}
            {{- with $.Values.common.secret}}
            - secretRef:
                name: {{ include "application.fullname" $ }}-common
            {{- end }}
          {{- end }}
          {{- with .commands }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- include "template.resources" (.resources | default dict ) | nindent 12}}
{{- end }}
{{- end }}
{{- end }}
{{- end }}