  
{{- with .Values.common.secret }}
{{- if . }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "application.fullname" $ }}-common
  labels:
    {{- include "get.labels.full" $ | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-9999"
    "helm.sh/hook": "pre-install"

data:
  {{- range $k, $v := . }}
  {{ $k }}: {{ $v | default "" | b64enc }}
  {{- end }}
{{- end }}
{{- end }}

{{- range .Values.apps }}
{{- if .secret }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .name }}-app
  {{- with include "get.labels.full" (list $ .labels) }}
  labels:
    {{ . | nindent 4 }}
  {{- end}}
  annotations:
    "helm.sh/hook-weight": "-9999"
    "helm.sh/hook": "pre-install"
data:
  {{- range $k, $v := . }}
  {{ $k }}: {{ $v | default "" | b64enc }}
  {{- end }}
{{- end }}
{{- end }}

{{- range .Values.apps }}
{{- range .jobs }}
{{- if .secret }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-job-%s" (include "application.fullname" $) (.name)}}
  {{- with include "get.labels.full" (list $ .labels) }}
  labels:
    {{- . | nindent 4 }}
  {{- end}}
  annotations:
    "helm.sh/hook-weight": "-9999"
    "helm.sh/hook": "pre-install"
data:
  {{- range $k, $v := .secret }}
  {{ $k }}: {{ $v | default "" | b64enc }}
  {{- end }}
{{- end }}
{{- end }}

{{- range .Values.workers }}
{{- if .secret }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-job-%s" (include "application.fullname" $) (.name)}}
  {{- with include "get.labels.full" (list $ .labels) }}
  labels:
    {{ . | nindent 4 }}
  {{- end}}
  annotations:
    "helm.sh/hook-weight": "-9999"
    "helm.sh/hook": "pre-install"
data:
  {{- range $k, $v := .secret }}
  {{ $k }}: {{ $v | default "" | b64enc }}
  {{- end }}
{{- end }} 
{{- end }} 
{{- end }} 
