{{- range .Values.apps -}}
{{- with (include "template.app" . )| fromYaml }}
{{- if .port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" $ }}
  {{- with include "get.labels.full" (list $ .labels) }}
  {{- . | nindent 2 }}
  {{- end}}
  {{- with include "get.annotations" (list $ .annotations) }}
  {{ . | nindent 2 }}
  {{- end}}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
  selector:
    {{- include "get.labels.selector" (list $ .labels) | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
